### ISSUE TITLE
Ignore apps

### ISSUE THREAD

**Issue by leonardt** [puffnfresh/Honer.app#2]
A way to ignore certain apps would be nice.

Example: Highlights Alfred.app popup which I don't think needs to be done.

**Comment by nittanycolonial** [comment]
I would also love to see this implemented. Or maybe just an option to turn Honer on & off, without having to quit it. I only have one app that I really need Honer for, I don't need it all the time. Otherwise, it's a very handy tool.

**Comment by nittanycolonial** [comment]
I actually decided to do something about this one and wrote the enhancement myself. This should be addressed in pull request #6 

I hope this project is still being supported at the base fork - I have no idea if it is.
