### ISSUE TITLE
Icon does not change color in Dark Mode

### ISSUE THREAD

**Issue by gwerbin** [puffnfresh/Honer.app#8]
Would be a nice feature! I use F.lux and have it set to turn on Dark Mode at night.

I found instructions [here](https://nsrover.wordpress.com/2014/10/10/creating-a-os-x-menubar-only-app/), in particular the line `[_statusItem.image setTemplate:YES];`. I'd make a PR myself, but I'm not sure where to put it in the code.

**Comment by joelbrewster** [comment]
There's a release in my fork that has this:
https://github.com/joelbrewster/Honer.app/releases
I'll keep it updated/remove it if needed.
